In [1]:
import cv2
import numpy as np
import os
import smtplib
import winsound
import pyautogui

In [2]:
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import socket
socket.getaddrinfo('localhost', 8080)

[(<AddressFamily.AF_INET6: 23>, 0, 0, '', ('::1', 8080, 0, 0)),
 (<AddressFamily.AF_INET: 2>, 0, 0, '', ('127.0.0.1', 8080))]

In [3]:
face_classifier = cv2.CascadeClassifier("haarcascades/haarcascade_frontalface_default.xml")

In [36]:
def face_extractor(img):

    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5)

    if faces is ():
        return None

    for(x,y,w,h) in faces:
        cropped_face = img[y:y+h,x:x+w]

    return cropped_face



cap = cv2.VideoCapture(0)
count=0

while True:
    ret,frame = cap.read()
    if face_extractor(frame) is not None:
        count+=1
        face = cv2.resize(face_extractor(frame),(200,200))
        face = cv2.cvtColor(face,cv2.COLOR_BGR2GRAY)

        file_name_path = "C:/Users/Aditya Sonawane/Desktop/face recognition/user"+str(count)+'.jpg'
        cv2.imwrite(file_name_path,face)

        cv2.putText(face,str(count),(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)
        cv2.imshow('Face Cropper',face)

    else:
        print("Face not found !!")
        pass

    if cv2.waitKey(1) == 13 or count == 150:
        break

cap.release()
cv2.destroyAllWindows()
print("Collecting samples completed *_*")

<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-36-4f210a0c0114>:6: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [4]:
from os import listdir           
from os.path import isfile,join

In [5]:
data_path = "C:/Users/Aditya Sonawane/Desktop/face recognition/user/"
onlyfiles = [f for f in listdir(data_path) if isfile(join(data_path,f))]

Training_Data,Labels = [],[]

for i,files in enumerate(onlyfiles):
    image_path = data_path + onlyfiles[i]
    images = cv2.imread(image_path,cv2.IMREAD_GRAYSCALE)
    Training_Data.append(np.asarray(images,dtype=np.uint8))
    Labels.append(i)

Labels = np.asarray(Labels,dtype=np.int32)

model = cv2.face.LBPHFaceRecognizer_create()



model.train(np.asarray(Training_Data),np.asarray(Labels))


face_classifier = cv2.CascadeClassifier("haarcascades/haarcascade_frontalface_default.xml")

In [31]:
len(Training_Data), len(Labels)

(150, 150)

In [32]:
Training_Data

[array([[ 65,  54,  45, ..., 211, 212, 213],
        [ 58,  46,  38, ..., 211, 211, 212],
        [ 57,  44,  35, ..., 212, 212, 212],
        ...,
        [188, 188, 188, ..., 219, 220, 220],
        [188, 188, 188, ..., 219, 219, 220],
        [188, 188, 188, ..., 218, 218, 218]], dtype=uint8),
 array([[ 35,  34,  36, ..., 221, 221, 221],
        [ 36,  35,  36, ..., 221, 221, 220],
        [ 37,  35,  35, ..., 222, 222, 221],
        ...,
        [196, 197, 198, ..., 229, 228, 228],
        [197, 198, 198, ..., 229, 228, 227],
        [197, 198, 198, ..., 229, 229, 228]], dtype=uint8),
 array([[ 52,  49,  42, ..., 212, 214, 214],
        [ 50,  47,  41, ..., 213, 214, 214],
        [ 45,  42,  37, ..., 214, 214, 215],
        ...,
        [193, 193, 194, ..., 233, 232, 233],
        [193, 193, 194, ..., 233, 233, 233],
        [192, 192, 193, ..., 232, 233, 233]], dtype=uint8),
 array([[ 41,  37,  32, ..., 213, 213, 213],
        [ 38,  36,  32, ..., 213, 213, 213],
        [ 34,  3

In [33]:
Training_Data = np.array(Training_Data)/255.0

In [34]:
Training_Data

array([[[0.25490196, 0.21176471, 0.17647059, ..., 0.82745098,
         0.83137255, 0.83529412],
        [0.22745098, 0.18039216, 0.14901961, ..., 0.82745098,
         0.82745098, 0.83137255],
        [0.22352941, 0.17254902, 0.1372549 , ..., 0.83137255,
         0.83137255, 0.83137255],
        ...,
        [0.7372549 , 0.7372549 , 0.7372549 , ..., 0.85882353,
         0.8627451 , 0.8627451 ],
        [0.7372549 , 0.7372549 , 0.7372549 , ..., 0.85882353,
         0.85882353, 0.8627451 ],
        [0.7372549 , 0.7372549 , 0.7372549 , ..., 0.85490196,
         0.85490196, 0.85490196]],

       [[0.1372549 , 0.13333333, 0.14117647, ..., 0.86666667,
         0.86666667, 0.86666667],
        [0.14117647, 0.1372549 , 0.14117647, ..., 0.86666667,
         0.86666667, 0.8627451 ],
        [0.14509804, 0.1372549 , 0.1372549 , ..., 0.87058824,
         0.87058824, 0.86666667],
        ...,
        [0.76862745, 0.77254902, 0.77647059, ..., 0.89803922,
         0.89411765, 0.89411765],
        [0.7

In [35]:
len(Training_Data[0])

200

In [36]:
Training_Data = np.resize(Training_Data, (150 ,100, 100  ,1))
Training_Data

array([[[[0.25490196],
         [0.21176471],
         [0.17647059],
         ...,
         [0.30196078],
         [0.30196078],
         [0.30588235]],

        [[0.3254902 ],
         [0.3372549 ],
         [0.3372549 ],
         ...,
         [0.82745098],
         [0.83137255],
         [0.83529412]],

        [[0.22745098],
         [0.18039216],
         [0.14901961],
         ...,
         [0.31764706],
         [0.31764706],
         [0.31764706]],

        ...,

        [[0.44705882],
         [0.44313725],
         [0.44313725],
         ...,
         [0.87843137],
         [0.87843137],
         [0.87843137]],

        [[0.77254902],
         [0.69803922],
         [0.42745098],
         ...,
         [0.47058824],
         [0.4627451 ],
         [0.45490196]],

        [[0.45098039],
         [0.44705882],
         [0.44705882],
         ...,
         [0.87843137],
         [0.87843137],
         [0.87843137]]],


       [[[0.76862745],
         [0.7372549 ],
         [0.50

In [37]:
from keras.utils.np_utils import to_categorical
from tensorflow.keras import utils as np_utils

In [44]:
Labels = np_utils.to_categorical(Labels)

In [62]:
Labels = np.resize(Labels, (150 ,2))


In [63]:
from sklearn.model_selection import train_test_split

In [64]:
X_train, X_test, Y_train, Y_test = train_test_split(Training_Data, Labels)

In [65]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((112, 100, 100, 1), (112, 2), (38, 100, 100, 1), (38, 2))

In [66]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPooling2D, Dropout, Flatten
from tensorflow.keras.optimizers import RMSprop
from keras.callbacks import ModelCheckpoint

In [67]:
model = Sequential()
model.add(Conv2D(200, (3,3), input_shape=(100, 100, 1)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(100, (3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Dropout(0.3))
model.add(Flatten())

model.add(Dense(50, activation='relu'))
model.add(Dense(2, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [71]:
cp = ModelCheckpoint('best_one', verbose=0, save_best_only=True)
model.fit(X_train, Y_train, epochs = 3 , callbacks=[cp], validation_split=0.2)

Epoch 1/3
3/3 [==============================] - 5s 2s/step - loss: 0.0000e+00 - accuracy: 0.6180 - val_loss: 0.0099 - val_accuracy: 0.0435
INFO:tensorflow:Assets written to: best_one\assets
Epoch 2/3
3/3 [==============================] - 6s 2s/step - loss: 0.0379 - accuracy: 0.6966 - val_loss: 0.1143 - val_accuracy: 0.9565
Epoch 3/3
3/3 [==============================] - 6s 2s/step - loss: 0.4427 - accuracy: 0.3483 - val_loss: 3.8156 - val_accuracy: 0.9565


In [72]:
from keras.models import load_model

In [73]:
model = load_model('best_one')

In [6]:
face_classifier = cv2.CascadeClassifier("haarcascades/haarcascade_frontalface_default.xml")

In [7]:
def face_detector(img,size = 0.5):
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5)

    if faces is():
        return img,[]

    for(x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h,x:x+w]
        roi = cv2.resize(roi,(200,200))

    return img,roi

cap = cv2.VideoCapture(0)
while True:
    ret,frame = cap.read()
    image , face = face_detector(frame)


    try:
        face = cv2.cvtColor(face,cv2.COLOR_BGR2GRAY)
        result = model.predict(face)

        
        if result[1] < 500:
            Confidence = int(100 * (1 - (result[1])/300))
            display_string = str(Confidence)+'% Matching Aditya'
        cv2.putText(image,display_string,(200,120),cv2.FONT_HERSHEY_COMPLEX,1,(250,120,255),2)

        
        if Confidence > 75:        
            
            cv2.putText(image, "AUTHORIZED", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 255, 0), 2)
            cv2.imshow("Face Cropper",image)
              
                
        else:
            
            cv2.putText(image, "CAN'T RECOGNISE UNAUTHORIZED", (50, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
            cv2.imshow("Face Cropper", image)
            winsound.PlaySound('alert (2).wav', winsound.SND_ASYNC)
            image = pyautogui.screenshot()
            image = cv2.cvtColor(np.array(image),cv2.COLOR_RGB2BGR)
            cv2.imwrite("INTRUDER.png", image)
            
            fromaddr = "aditya77458689@gmail.com"
            toaddr = "sonawaneaditya8689@gmail.com"
            msg = MIMEMultipart()
            msg['aditya77458689@gmail.com'] = fromaddr
            msg['sonawaneaditya8689@gmail.com'] = toaddr
            msg['Subject'] = "!!! SAFETY COMPROMISED !!!"
            body = "A person is found trespassing on your property setting of alarm"
            msg.attach(MIMEText(body, 'plain'))
            filename = "INTRUDER.png"
            attachment = open("INTRUDER.png", "rb")
            p = MIMEBase('application', 'octet-stream')
            p.set_payload((attachment).read())
            encoders.encode_base64(p)
            p.add_header('Content-Disposition', "attachment; filename= %s" % filename)
            msg.attach(p)
            s = smtplib.SMTP('smtp.gmail.com', 587)
            s.starttls()
            s.login(fromaddr, "aditya*^*(")
            text = msg.as_string()
            s.sendmail(fromaddr, toaddr, text)
            s.quit()

   
            
        
    except:
       
        cv2.putText(image, "Face not Found", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 0, 0), 2)
        cv2.imshow("Face Cropper", image)
        pass
    if cv2.waitKey(1) == 27:
        break
cap.release()
cv2.destroyAllWindows()

<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-7-ace484eec92f>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is():
